version: 1
jobs:
  build:
    docker:
      - image: circleci/node:9

    steps:
      - checkout

      - run: sudo npm install -g npm@latest

      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: Build
          command: npm run prod

  publish:
    docker:
      - image: circleci/node:9

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish
          command: npm publish ./

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
